version: '3.7'
services:
  mysql:
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_DATABASE=gcommerce
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    image: rabbitmq:3.9.29-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
  gcommerce-orders:
    build: .
    container_name: gcommerce-orders
    env_file: variables.env
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/app
      - $HOME/go/pkg/mod:/go/pkg/mod