// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

type Requester_Expecter struct {
	mock *mock.Mock
}

func (_m *Requester) EXPECT() *Requester_Expecter {
	return &Requester_Expecter{mock: &_m.Mock}
}

// Post provides a mock function with given fields: url, contentType, body
func (_m *Requester) Post(url string, contentType string, body io.Reader) (*http.Response, error) {
	ret := _m.Called(url, contentType, body)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) (*http.Response, error)); ok {
		return rf(url, contentType, body)
	}
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) *http.Response); ok {
		r0 = rf(url, contentType, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(url, contentType, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Requester_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type Requester_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - contentType string
//   - body io.Reader
func (_e *Requester_Expecter) Post(url interface{}, contentType interface{}, body interface{}) *Requester_Post_Call {
	return &Requester_Post_Call{Call: _e.mock.On("Post", url, contentType, body)}
}

func (_c *Requester_Post_Call) Run(run func(url string, contentType string, body io.Reader)) *Requester_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *Requester_Post_Call) Return(_a0 *http.Response, _a1 error) *Requester_Post_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Requester_Post_Call) RunAndReturn(run func(string, string, io.Reader) (*http.Response, error)) *Requester_Post_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRequester interface {
	mock.TestingT
	Cleanup(func())
}

// NewRequester creates a new instance of Requester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRequester(t mockConstructorTestingTNewRequester) *Requester {
	mock := &Requester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
